### PR TITLE
Trovo uses HLS for VOD streams

### PR DESCRIPTION
**Pull request by CeruleanSky**
Add support for video on demand streams that use HLS instead.  Live continues to use HTTP.

### CODE REVIEW

**Comment by CeruleanSky** [comment]
@nedsed Should work again for live and vod streams. I don't use trovo very often so I may or may not be updating my fork and this pull request in the future.

**Comment by nedsed** [comment]
Works! Thank you very much for taking the time.

**Comment by nedsed** [comment]
Looks like Trovo made a change breaking the downloader again. 😇

**Comment by ReZer0-Y** [comment]
> Looks like Trovo made a change breaking the downloader again. 😇

Yep, don't know if you found a workaround, I'm stuck with this right now.

**Pull request closed without merging**
